apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: traefik-ingress
spec:
 rules:
   - host: 127.0.0.1.xip.io
     http:
       paths:
         - path: /
           backend:
             serviceName: nginx
             servicePort: 80