apiVersion: v1
kind: Service
metadata:
  name: java
  labels:
    app: java
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: java
    tier: java
  type: NodePort
  
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: java
  labels:
    app: java
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: java
        tier: java
    spec:
      containers:
      - image: java:8
        name: java
        command: ["/app/start.sh"]
        ports:
        - containerPort: 8080
          name: java
        volumeMounts:
        - name: app
          mountPath: /app
      volumes:
      - name: app
        hostPath:
          path: /apps/java

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
 name: java-ingress
spec:
 rules:
   - host: java.127.0.0.1.xip.io
     http:
       paths:
         - path: /
           backend:
             serviceName: java
             servicePort: 8080